version: '3.2'

services:
  rabbit:
    image: rabbitmq:3.13-management
    container_name: Coelho
    environment:
      - RABBITMQ_DEFAULT_USER="coelho"
      - RABBITMQ_DEFAULT_PASS="E73k@xG4Lx9%y!"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
